const capitals: Record<string, string> = {
  AD: "Andorra la Vella", AE: "Abu Dhabi", AF: "Kabul", AG: "Saint John's", AI: "The Valley",
  AL: "Tirana", AM: "Yerevan", AO: "Luanda", AR: "Buenos Aires", AS: "Pago Pago",
  AT: "Vienna", AU: "Canberra", AW: "Oranjestad", AX: "Mariehamn", AZ: "Baku",
  BA: "Sarajevo", BB: "Bridgetown", BD: "Dhaka", BE: "Brussels", BF: "Ouagadougou",
  BG: "Sofia", BH: "Manama", BI: "Gitega", BJ: "Porto-Novo", BL: "Gustavia",
  BM: "Hamilton", BN: "Bandar Seri Begawan", BO: "Sucre", BQ: "Kralendijk", BR: "Brasilia",
  BS: "Nassau", BT: "Thimphu", BW: "Gaborone", BY: "Minsk", BZ: "Belmopan",
  CA: "Ottawa", CC: "West Island", CD: "Kinshasa", CF: "Bangui", CG: "Brazzaville",
  CH: "Bern", CI: "Yamoussoukro", CK: "Avarua", CL: "Santiago", CM: "Yaounde",
  CN: "Beijing", CO: "Bogota", CR: "San Jose", CU: "Havana", CV: "Praia",
  CW: "Willemstad", CX: "Flying Fish Cove", CY: "Nicosia", CZ: "Prague", DE: "Berlin",
  DJ: "Djibouti", DK: "Copenhagen", DM: "Roseau", DO: "Santo Domingo", DZ: "Algiers",
  EC: "Quito", EE: "Tallinn", EG: "Cairo", EH: "Laayoune", ER: "Asmara",
  ES: "Madrid", ET: "Addis Ababa", FI: "Helsinki", FJ: "Suva", FK: "Stanley",
  FM: "Palikir", FO: "Torshavn", FR: "Paris", GA: "Libreville", GB: "London",
  GD: "Saint George's", GE: "Tbilisi", GF: "Cayenne", GG: "Saint Peter Port", GH: "Accra",
  GI: "Gibraltar", GL: "Nuuk", GM: "Banjul", GN: "Conakry", GP: "Basse-Terre",
  GQ: "Malabo", GR: "Athens", GT: "Guatemala City", GU: "Hagatna", GW: "Bissau",
  GY: "Georgetown", HK: "Hong Kong", HN: "Tegucigalpa", HR: "Zagreb", HT: "Port-au-Prince",
  HU: "Budapest", ID: "Jakarta", IE: "Dublin", IL: "Jerusalem", IM: "Douglas",
  IN: "New Delhi", IO: "Diego Garcia", IQ: "Baghdad", IR: "Tehran", IS: "Reykjavik",
  IT: "Rome", JE: "Saint Helier", JM: "Kingston", JO: "Amman", JP: "Tokyo",
  KE: "Nairobi", KG: "Bishkek", KH: "Phnom Penh", KI: "South Tarawa", KM: "Moroni",
  KN: "Basseterre", KP: "Pyongyang", KR: "Seoul", KW: "Kuwait City", KY: "George Town",
  KZ: "Astana", LA: "Vientiane", LB: "Beirut", LC: "Castries", LI: "Vaduz",
  LK: "Sri Jayawardenepura Kotte", LR: "Monrovia", LS: "Maseru", LT: "Vilnius", LU: "Luxembourg",
  LV: "Riga", LY: "Tripoli", MA: "Rabat", MC: "Monaco", MD: "Chisinau",
  ME: "Podgorica", MF: "Marigot", MG: "Antananarivo", MH: "Majuro", MK: "Skopje",
  ML: "Bamako", MM: "Naypyidaw", MN: "Ulaanbaatar", MO: "Macao", MP: "Saipan",
  MQ: "Fort-de-France", MR: "Nouakchott", MS: "Brades", MT: "Valletta", MU: "Port Louis",
  MV: "Male", MW: "Lilongwe", MX: "Mexico City", MY: "Kuala Lumpur", MZ: "Maputo",
  NA: "Windhoek", NC: "Noumea", NE: "Niamey", NF: "Kingston", NG: "Abuja",
  NI: "Managua", NL: "Amsterdam", NO: "Oslo", NP: "Kathmandu", NR: "Yaren",
  NU: "Alofi", NZ: "Wellington", OM: "Muscat", PA: "Panama City", PE: "Lima",
  PF: "Papeete", PG: "Port Moresby", PH: "Manila", PK: "Islamabad", PL: "Warsaw",
  PM: "Saint-Pierre", PN: "Adamstown", PR: "San Juan", PS: "Ramallah", PT: "Lisbon",
  PW: "Ngerulmud", PY: "Asuncion", QA: "Doha", RE: "Saint-Denis", RO: "Bucharest",
  RS: "Belgrade", RU: "Moscow", RW: "Kigali", SA: "Riyadh", SB: "Honiara",
  SC: "Victoria", SD: "Khartoum", SE: "Stockholm", SG: "Singapore", SH: "Jamestown",
  SI: "Ljubljana", SJ: "Longyearbyen", SK: "Bratislava", SL: "Freetown", SM: "San Marino",
  SN: "Dakar", SO: "Mogadishu", SR: "Paramaribo", SS: "Juba", ST: "Sao Tome",
  SV: "San Salvador", SX: "Philipsburg", SY: "Damascus", SZ: "Mbabane", TC: "Cockburn Town",
  TD: "N'Djamena", TF: "Port-aux-Francais", TG: "Lome", TH: "Bangkok", TJ: "Dushanbe",
  TK: "Nukunonu", TL: "Dili", TM: "Ashgabat", TN: "Tunis", TO: "Nuku'alofa",
  TR: "Ankara", TT: "Port of Spain", TV: "Funafuti", TW: "Taipei", TZ: "Dodoma",
  UA: "Kyiv", UG: "Kampala", US: "Washington, D.C.", UY: "Montevideo", UZ: "Tashkent", VA: "Vatican City",
  VC: "Kingstown", VE: "Caracas", VG: "Road Town", VI: "Charlotte Amalie", VN: "Hanoi",
  VU: "Port Vila", WF: "Mata-Utu", WS: "Apia", YE: "Sana'a", YT: "Mamoudzou",
  ZA: "Pretoria", ZM: "Lusaka", ZW: "Harare", XK: "Pristina",
};

export function countryCapital(code: string) {
  return capitals[code.toUpperCase()];
}
